// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYaHZfEzljoIoBhCaZwE2tvr7fFAytvSY',
    appId: '1:604372960262:web:db02b0627bb8bbc0ae2f87',
    messagingSenderId: '604372960262',
    projectId: 'parivartan-cf299',
    authDomain: 'parivartan-cf299.firebaseapp.com',
    storageBucket: 'parivartan-cf299.firebasestorage.app',
    measurementId: 'G-GNJHL891WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdO81qJ-4H3rBfaKdcqff2Y-rMLQ5GTeA',
    appId: '1:604372960262:android:63b2fac6243f7eeeae2f87',
    messagingSenderId: '604372960262',
    projectId: 'parivartan-cf299',
    storageBucket: 'parivartan-cf299.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgP_WhSo7YKTDMR-IaLSxZZRjPhIdt_BY',
    appId: '1:604372960262:ios:03edf5c10fa04349ae2f87',
    messagingSenderId: '604372960262',
    projectId: 'parivartan-cf299',
    storageBucket: 'parivartan-cf299.firebasestorage.app',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgP_WhSo7YKTDMR-IaLSxZZRjPhIdt_BY',
    appId: '1:604372960262:ios:03edf5c10fa04349ae2f87',
    messagingSenderId: '604372960262',
    projectId: 'parivartan-cf299',
    storageBucket: 'parivartan-cf299.firebasestorage.app',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYaHZfEzljoIoBhCaZwE2tvr7fFAytvSY',
    appId: '1:604372960262:web:91bf658e049bf2e4ae2f87',
    messagingSenderId: '604372960262',
    projectId: 'parivartan-cf299',
    authDomain: 'parivartan-cf299.firebaseapp.com',
    storageBucket: 'parivartan-cf299.firebasestorage.app',
    measurementId: 'G-R7PHS4ZWNM',
  );
}
